services:
  nostr-rs-relay:
    image: scsibug/nostr-rs-relay:latest
    ports:
      - "7000:8080"
    volumes:
      - ./config.toml:/usr/src/app/config.toml
      - ./data:/usr/src/app/db
    stdin_open: true
    tty: true
